main:
  - name: Details
    url: '/details/'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Notes
    url: /notes/
    weight: 3
  - name: Projects
    url: /Projects/
    weight: 4
